export enum PostTypes {
  TEXT = 'text',
  BASIC = 'basic',
  JAVASCRIPT = 'javascript',
  PASCAL = 'pascal',
  CPP = 'cpp',
  ONE_C = '1c',
  PROLOG = 'prolog',
  CS = 'cs',
  PHP = 'php',
  CSS = 'css',
  SQL = 'sql',
  LESS = 'less',
  STYLUS = 'stylus',
  NGINX = 'nginx',
  GO = 'go',
  TYPESCRIPT = 'typescript',
  DART = 'dart',
}
